# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mathe ist kein Arschloch!
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Mathematik für Studenten einfach erklärt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matheistkeinarschloch.de" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

navigation:
  - title: Lineare Algebra
    subitems:
      - title: Gruppen, Ringe, Körper
        url: /gruppen-ringe-koerper/
      - title: Induktion (Beweismethode)
        url: /induktion/
      - title: Lineare Unabhängigkeit
        url: /lineare-unabhaengigkeit/
      - title: Eigenwerte und Eigenvektoren
        url: /eigenwert-und-eigenvektoren/
      - title: Invertierbare Matrizen und ihre Eigenschaften
        url: /invertierbare-matrizen-und-ihre-eigenschaften/
      - title: Diagonalisierbarkeit von Matrizen
        url: /diagonalisierbarkeit-von-matrizen/
  - title: Analysis
    subitems:
      - title: Folgen und Grenzwerte
        url: /folgen-und-grenzwerte/
      - title: Reihen - Grundlagen
        url: /reihen-grundlagen/
      - title: Reihen - Konvergenzkriterien und Beispiele
        url: /reihen-konvergenzkriterien-und-beispiele/
      - title: Die injektive, surjektive, bijektive Kneipenprügelei
        url: /die-injektive-surjektive-bijektive-kneipenpruegelei/
      - title: Monotonie
        url: /monotonie/
      - title: Stetigkeit
        url: /stetigkeit/
      - title: Taylor-Polynome
        url: /taylor-polynome/
      - title: Polarkoordinaten
        url: /polarkoordinaten/
      - title: Komplexe Zahlen - Grundlagen
        url: /komplexe-zahlen-grundlagen/
      - title: Mehrdimensionales Ableiten
        url: /mehrdimensionales-ableiten/
      - title: Mehrdimensionale Integration
        url: /mehrdimensionale-integration/
      - title: Mehrdimensionale Integrale - "Gegenbeispiel" zum Satz von Fubini
        url: /mehrdimensionale-integrale-gegenbeispiel-zum-satz-von-fubini/
      - title: Optimieren unter Nebenbedingungen (Lagrange)
        url: /optimieren-unter-nebenbedingungen-lagrange/
  - title: Statistik
    subitems:
      - title: Binomialtest
        url: /binomialtest/
      - title: Chi-Quadrat-Test
        url: /chi-quadrat-test/
      - title: T-Test (zwei Stichproben)
        url: /t-test-zwei-stichproben/
  - title: Über diese Seite
    subitems:
      - title: Über mich
        url: /ueber-mich/
      - title: Datenschutzerklärung
        url: /datenschutz/
      - title: Haftungsausschluss
        url: /haftungsausschluss/
      - title: Impressum
        url: /impressum/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
